#การรับค่าข้อมูลทางแป้นพิมพ์ด้วย Python
name = input('ป้อนชื่อ: ')
yearBorn = input('ป้อนปีเกิด: ')
print('---------------------------')
#ฟังก์ชันในการแปลงข้อมูลจากข้อความเป็นตัวเลข int( ), fioat( )
#ฟังก์ชันในการแปลงข้อมูลจากตัวเลขเป็นข้อความ str( )
print(f'ยินดีต้อนรับคุณ {name} เกิดปี {yearBorn} อายุ {2023-int(yearBorn) }')
print('ยินดีต้อนรับคุณ',name,'เกิดปี',yearBorn,'อายุ',2023-int(yearBorn))
print('ยินดีต้อนรับคุณ '+name+' เกิดปี '+yearBorn+' อายุ '+ str(2023-int(yearBorn)))
print('ยินดีต้อนรับคุณ {} เกิดปี {} อายุ {}'.format(name,yearBorn,2023 - int(yearBorn)))
print('ยินดีต้อนรับคุณ %s เกิดปี %s อายุ %d' %(name,yearBorn,2023 - int(yearBorn)))